In [1]:

# TASK 1: Data Immersion & Wrangling
# Dataset: sales_data.csv


import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("sales_data.csv")

print("First 5 rows of dataset:")
display(df.head())

print("\nDataset Info:")
df.info()

print("\nSummary Statistics:")
display(df.describe())

print("\nMissing Values Check:")
display(df.isnull().sum())

print("\nDuplicate Rows Check:")
print("Number of duplicate rows:", df.duplicated().sum())


#Remove Duplicates
df = df.drop_duplicates()

print("\nShape After Removing Duplicates:", df.shape)


# Data Validation Checks
print("\nNegative Value Check:")
display((df[['total_bill','tip']] < 0).sum())

print("\nInvalid Tip Check (tip > total_bill):")
print((df['tip'] > df['total_bill']).sum())


# Tip percentage (Decimal format for Data Science)
df['tip_percentage'] = df['tip'] / df['total_bill']

df['revenue_per_person'] = df['total_bill'] / df['size']
df['tip_per_person'] = df['tip'] / df['size']

print("\nFeature Engineering Completed.")
display(df.head())


#Data Type Optimization
df['sex'] = df['sex'].astype('category')
df['smoker'] = df['smoker'].astype('category')
df['day'] = df['day'].astype('category')
df['time'] = df['time'].astype('category')

print("\nUpdated Data Types:")
df.info()


print("\nFinal Dataset Shape:", df.shape)
print("\nFinal Dataset Preview:")
display(df.head())


df.to_csv("cleaned_sales_data.csv", index=False)

print("\nCleaned dataset exported successfully.")

files.download("cleaned_sales_data.csv")

Saving sales_data.csv to sales_data.csv
First 5 rows of dataset:

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

Summary Statistics:

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Missing Values Check:

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

Duplicate Rows Check:
Number of duplicate rows: 1

Shape After Removing Duplicates: (243, 7)

Negative Value Check:

total_bill    0
tip           0
dtype: int64

Invalid Tip Check (tip > total_bill):
0

Feature Engineering Completed.

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,revenue_per_person,tip_per_person
0,16.99,1.01,Female,No,Sun,Dinner,2,0.059447,8.495000,0.505000
1,10.34,1.66,Male,No,Sun,Dinner,3,0.160542,3.446667,0.553333
2,21.01,3.50,Male,No,Sun,Dinner,3,0.166587,7.003333,1.166667
3,23.68,3.31,Male,No,Sun,Dinner,2,0.139780,11.840000,1.655000
4,24.59,3.61,Female,No,Sun,Dinner,4,0.146808,6.147500,0.902500

Updated Data Types:
<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, 0 to 243
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   total_bill          243 non-null    float64
 1   tip                 243 non-null    float64
 2   sex                 243 non-null    category
 3   smoker              243 non-null    category
 4   day                 243 non-null    category
 5   time                243 non-null    category
 6   size                243 non-null    int64
 7   tip_percentage      243 non-null    float64
 8   revenue_per_person  243 non-null    float64
 9   tip_per_person      243 non-null    float64
dtypes: category(4), float64(5), int64(1)
memory usage: 14.8 KB

Final Dataset Shape: (243, 10)

Final Dataset Preview:

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,revenue_per_person,tip_per_person
0,16.99,1.01,Female,No,Sun,Dinner,2,0.059447,8.495000,0.505000
1,10.34,1.66,Male,No,Sun,Dinner,3,0.160542,3.446667,0.553333
2,21.01,3.50,Male,No,Sun,Dinner,3,0.166587,7.003333,1.166667
3,23.68,3.31,Male,No,Sun,Dinner,2,0.139780,11.840000,1.655000
4,24.59,3.61,Female,No,Sun,Dinner,4,0.146808,6.147500,0.902500

Cleaned dataset exported successfully.